name: thyroid_cancer_chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - pip
  - pip:
    - streamlit==1.37.0
    - langchain
    - openai
    - langchain-experimental
    - tiktoken
    - faiss-cpu
    - langchain-openai
    - langchain-community
    - pdfplumber
